# Generated by Django 5.1.1 on 2024-10-21 15:23

import apiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=apiApp.models.user_directory_path),
        ),
    ]
